services:
  abiotic-server:
    container_name: abiotic-server
    image: ghcr.io/pleut/abiotic-factor-linux-docker:latest
    restart: unless-stopped
    volumes:
      - ./gamefiles:/server
      - ./data:/server/AbioticFactor/Saved
    environment:
      - MaxServerPlayers=6
      - Port=7777
      - QueryPort=27015
      - ServerPassword=password
      - SteamServerName=Linux Server
      - UsePerfThreads=true
      - NoAsyncLoadingThread=true
      - WorldSaveName=Mobo_Blob
      - AutoUpdate=true
      - AdditionalArgs=-SandboxIniPath=Config/WindowsServer/Sandbox.ini
    depends_on:
      - powercore95
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:27015:27015/udp"

  powercore95:
    container_name: powercore95
    image: docker.io/radicalegg/powercore95:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/gamedata
    ports:
      - 9090:9090
    environment:
      CONTAINER_NAME: abiotic-server # abiotic-server container name for restarts
      SERVER_NAME: Mobo Blob # Sets the header on the dashboard, not related to the abiotic-server container
      SANDBOX_INI_PATH: /gamedata/Config/WindowsServer/Sandbox.ini # this default and does not need to be explicitly set
